import os
import httpx
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

# PUBLIC_INTERFACE
class ChatRequest(BaseModel):
    prompt: str = Field(..., description="Prompt for the OpenAI chatbot")

# PUBLIC_INTERFACE
class ChatResponse(BaseModel):
    response: str = Field(..., description="Response generated by the OpenAI chatbot")

router = APIRouter()

OPENAI_ENDPOINT = "https://api.openai.com/v1/chat/completions"

# PUBLIC_INTERFACE
@router.post(
    "/chat",
    response_model=ChatResponse,
    summary="OpenAI Chatbot Endpoint",
    description="Send a prompt to the OpenAI chatbot and receive a generated response.",
    tags=["chat"]
)
async def chat(request: ChatRequest):
    """
    PUBLIC_INTERFACE
    Sends a user prompt to the OpenAI chat API and returns the AI's response.
    
    Parameters:
    - prompt (str): The user message to send to the chatbot.
    
    Returns:
    - response (str): The AI-generated reply to the prompt.
    """
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise HTTPException(status_code=500, detail="OpenAI API key not configured in environment variables.")

    payload = {
        "model": "gpt-3.5-turbo",
        "messages": [
            {"role": "user", "content": request.prompt}
        ]
    }

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }

    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(OPENAI_ENDPOINT, json=payload, headers=headers, timeout=25)
        response.raise_for_status()
        data = response.json()
        message = data['choices'][0]['message']['content']
        return ChatResponse(response=message)
    except httpx.HTTPStatusError as err:
        raise HTTPException(status_code=502, detail=f"OpenAI API error: {err.response.text}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error communicating with OpenAI: {str(e)}")
